### ISSUE TITLE
Provide a bash script to download and install the Eclipse/server part

### ISSUE THREAD

**Issue by JulioJu** [dansomething/vim-eclim#2]
Hi,

Maybe it could be cool to provide a bash script who download the eclim binary to install the Eclipse part of this plugin (in folder /opt/eclipse, or an other). 

During the installation of `https://github.com/ervandew/eclim/releases/download/2.7.1/eclim_2.7.1.bin`. At the question « 
`Please specify the directory where you would like the eclim vimfiles installed.
If you do not want to install the vimfiles (eg: emacs-eclim users), then type: skip` », we must type « skip »… 

It could be interesting because it ensure that client/vim part of the plugin correspond of the Eclipse/server part of the plugin ? 

In the README, we could advise to put in the vimrc for example:
```vim
Plug 'dansomething/vim-eclim', { 'for': ['java', 'xml', …… ], 'do': 'bash install.sh' }
```

What do you think about that ?

**Comment by dansomething** [comment]
@JulioJu thanks for the suggestion. Its a great idea, but I'm super short of time. I'm open to a pull request though.

**Comment by dansomething** [comment]
@JulioJu I added an `install.sh` script in the root of the project on master. You're welcome to give it a shot. I consider it experimental at this point. Unfortunately, I can't make any safe assumptions about where Eclipse is installed or what plugins to enable so you'll have to specify those yourself. All script args are passed through directly to the eclim installer.
http://eclim.org/install.html#interactive-command-line-installer

For now, all I've done is enable the unattended install and skip vimfiles.

Here's an example that should work depending on your Eclipse location.
```
Plug 'dansomething/vim-eclim', { 'for': ['java', 'groovy', 'html'], 'do': './install.sh --eclipse=/Applications/Eclipse.app --plugins=jdt,wst,groovy }
```

**Comment by JulioJu** [comment]
@dansomething 
Ok thanks… Il will test.
Be carreful, don hot put `html` in command line due to https://github.com/Shougo/deoplete.nvim/issues/709 !
